version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpassword
      POSTGRES_DB: prod
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  
  shortener:
    container_name: shortener
    env_file: .env
    depends_on:
      - redis
      - db
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"

volumes:
  db:
  cache:
